clone:
  clone:
    image: plugins/git
    tags: true

pipeline:
  test:
    image: images.borgy.elementai.net/borgy/plugin-pythons-testenv:latest
    secrets: [ COVERALLS_REPO_TOKEN, TWINE_USERNAME, TWINE_PASSWORD ]
    environment:
      - BORGY_RAM=8
      - BORGY_CPU=2
    commands:
      - export PIP_EXTRA_INDEX_URL="https://$TWINE_USERNAME:$TWINE_PASSWORD@pypi.elmt.io/repo/eai-core"
      - python3.7 -m venv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
      - pip install -r requirements-tests.txt
      - make test.full
      - coveralls
      - deactivate
      - rm -fr venv
    volumes:
      # Required for the process agent docker mode to work
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [ push, tag ]
      ref:
        exclude: [ refs/tags/latest, refs/tags/latest_test ]

  publish:
    image: images.borgy.elementai.net/borgy/plugin-python-release:latest
    secrets: [ github_token ]
    environment:
    - GITHUB_REPO=${DRONE_REPO_NAME}
    - GITHUB_USER=${DRONE_REPO_OWNER}
    commands:
    - make DPZ_RELEASE=1 package.build.process-agent
    - export DPZ_DISTRIB_BASE=/distrib/python
    - make DPZ_RELEASE=1 package.distrib.process-agent
    - echo "Install using:" >> /tmp/notes.txt
    - echo "pip install $(make package.distrib.process-agent.path)" | sed -e 's|/distrib|http://distrib.borgy.elementai.net|' >> /tmp/notes.txt
    - echo "OR" >> /tmp/notes.txt
    - echo "pip install --extra-index-url https://pypi.elmt.io/repo/eai-core  borgy-process-agent-api-server" >> /tmp/notes.txt
    - echo "" >> /tmp/notes.txt
    - echo "Changes:" >> /tmp/notes.txt
    - git log `git describe --tags HEAD^1 --abbrev=0`..HEAD --oneline >> /tmp/notes.txt
    # Always delete release on github first, ignoring the result. This is to make sure
    # that an update to a release moves it to the top.
    - export GOPATH=`pwd`/.env
    - /go/bin/github-release delete --tag ${DRONE_TAG} || true
    # Upload release to github
    - /go/bin/github-release release --tag ${DRONE_TAG} --name ${DRONE_TAG} --description "`cat /tmp/notes.txt`"
    volumes:
      - /mnt/borgy/distrib:/distrib
    when:
      event: tag
      ref:
        exclude: [ refs/tags/latest, refs/tags/latest_test ]

  publish_image:
    image: images.borgy.elementai.net/borgy/plugin-k8s-deploy:latest
    secrets: [ TWINE_USERNAME, TWINE_PASSWORD ]
    commands:
    # Publish docker image
    - set -x
    - env | sort
    - export PIP_EXTRA_INDEX_URL="https://$TWINE_USERNAME:$TWINE_PASSWORD@pypi.elmt.io/repo/eai-core"
    - version=$(set -x; echo "${DRONE_COMMIT_REF}" | sed -e 's|refs/tags/||g' | sed -e 's|refs/heads/||g')
    - export DPZ_RELEASE=1
    - export DPZ_VERSION=$version
    - export DPZ_FORCE_BUILD=1
    - make image.publish.process-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [ push, tag ]
      ref:
        include: [ refs/heads/dev, refs/tags/* ]

  trigger_dev_integration_tests:
    image: plugins/downstream
    server: https://drone.elementai.com:8443
    secrets: [ downstream_token ]
    fork: true
    repositories:
      - ElementAI/borgy@integration_tests_dev
    when:
      event: push
      branch: dev

  trigger_prod_integration_tests:
    image: plugins/downstream
    server: https://drone.elementai.com:8443
    secrets: [ downstream_token ]
    fork: true
    repositories:
      - ElementAI/borgy@integration_tests_prod
    when:
      event: tag
      ref: refs/tags/latest

  publish_pypi:
    image: images.borgy.elementai.net/borgy/plugin-pypi-release:latest
    secrets: [ TWINE_USERNAME, TWINE_PASSWORD ]
    commands:
    # Upload to pypi
    - export DPZ_DISTRIB_BASE=/distrib/python
    - twine upload --repository-url https://pypi.elmt.io/repo/eai-core $(make package.distrib.process-agent.path)
    volumes:
      - /mnt/borgy/distrib:/distrib
    when:
      event: tag
      ref:
        exclude: [ refs/tags/latest, refs/tags/latest_test ]

  update_latest:
    image: images.borgy.elementai.net/borgy/plugin-python-release:latest
    commands:
    - export DPZ_DISTRIB_BASE=/distrib/python
    - make DPZ_RELEASE=1 DPZ_VERSION=${DRONE_TAG} package.distrib.process-agent.latest
    volumes:
      - /mnt/borgy/distrib:/distrib
    when:
      event: tag
      ref: [ refs/tags/latest, refs/tags/latest_test ]

  notify_deployment:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: borgy-dev-events
    username: drone
    template: >
      {{#success build.status}}
        *${DRONE_REPO_NAME}* *${DRONE_TAG}* release succeeded.
      {{else}}
        *${DRONE_REPO_NAME}* *${DRONE_TAG}* release failed. Panic.
      {{/success}}
      {{build.author}}: {{build.message}} <{{build.link}}|build {{build.number}}>
    when:
      status: [ success, failure ]
      event: tag

  black_duck_scan:
   image: images.borgy.elementai.net/borgy/plugin-k8s-deploy:latest
   pull: true
   secrets: [ black_duck_api_key, TWINE_USERNAME, TWINE_PASSWORD ]
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   commands:
     - export PIP_EXTRA_INDEX_URL="https://$TWINE_USERNAME:$TWINE_PASSWORD@pypi.elmt.io/repo/eai-core"
     - make DPZ_BRANCH_NAME=$DRONE_BRANCH image.scan.process-agent
   when:
     event: [ push, tag ]
     ref:
       include: [ refs/heads/dev, refs/tags/* ]
       exclude: [ refs/tags/latest, refs/tags/latest_test ]
