FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y software-properties-common ca-certificates curl git libjpeg-dev build-essential make libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libyaml-dev \
    && apt-add-repository -y ppa:fkrull/deadsnakes \
    && apt-get update \
    && apt-get install -y python2.6 python2.7 python3.1 python3.2 python3.3 python3.4 python3.5 python3.6 \
                            python3.4-venv python3.5-venv python3.6-venv \
                            python2.6-dev python2.7-dev python3.1-dev python3.2-dev python3.3-dev python3.4-dev python3.5-dev python3.6-dev \
    && rm -rf /var/lib/apt/lists/*

CMD bash
